use Mix.Config

# Configure your database
config :trivium, Trivium.Repo,
  username: "postgres",
  password: "postgres",
  database: "trivium_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :trivium, Trivium.Repo.GIS,
  username: "psql_readonly",#   username: "psql_main",
  password: "postgres",#   password: "s3xyb1tch",
  database: "gis",
  hostname: "192.168.1.10",
  show_sensitive_data_on_connection_error: true,
  pool_size: 50,
  read_only: true

# config :trivium, Trivium.Repo.GIS,
#   username: "postgres_readonly",
#   password: "postgres",
#   database: "gis",
#   hostname: "localhost",
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 50,
#   read_only: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :trivium, TriviumWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  live_view: [
    signing_salt: "CBo0wjCUiAoeh2I9iMzGEiQKoLQ/WRfF"
  ],
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :trivium, TriviumWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/trivium_web/{live,views}/.*(ex)$",
      ~r"lib/trivium_web/templates/.*(eex)$",
      ~r{lib/trivium_web/live/.*(ex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
