theme: jekyll-theme-minimal
title: Trivium
name: Trivium
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://trivium.gg" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
